// Seletores reutilizáveis
export const selectors = {
  pageTitle: '[data-cy="pageTitle"]',
  companyForm: '[data-cy="companyForm"]',
  companyDataSection: '[data-cy="companyDataSection"]',
  cnpjInput: '[data-cy="cnpjInput"] input',
  cnpjInputElement: '[data-cy="cnpjInputElement"]',
  cnpjHelperText: ".MuiFormHelperText-root",
  cnpjGridContainer: '[data-cy="cnpjGridContainer"]',
  razaoSocialInput: '[data-cy="razaoSocialInput"] input',
  razaoSocialGridContainer: '[data-cy="razaoSocialGridContainer"]',
  nomeFantasiaInput: '[data-cy="nomeFantasiaInput"] input',
  nomeFantasiaGridContainer: '[data-cy="nomeFantasiaGridContainer"]',
  cepInput: '[data-cy="cepInput"] input',
  cepHelperText: '[data-cy="cepHelperText"]',
  cepGridContainer: '[data-cy="cepGridContainer"]',
  companyAddressSection: '[data-cy="companyAddressSection"]',
  estadoInput: '[data-cy="estadoInput"] input',
  estadoHelperText: '[data-cy="estadoHelperText"]',
  estadoGridContainer: '[data-cy="estadoGridContainer"]',
  municipioInput: '[data-cy="municipioInput"] input',
  municipioGridContainer: '[data-cy="municipioGridContainer"]',
  logradouroInput: '[data-cy="logradouroInput"] input',
  logradouroGridContainer: '[data-cy="logradouroGridContainer"]',
  numeroInput: '[data-cy="numeroInput"] input',
  numeroHelperText: '[data-cy="numeroHelperText"]',
  numeroGridContainer: '[data-cy="numeroGridContainer"]',
  complementoInput: '[data-cy="complementoInput"] input',
  complementoHelperText: '[data-cy="complementoHelperText"]',
  complementoGridContainer: '[data-cy="complementoGridContainer"]',
  submitButton: '[data-cy="submitButton"]',
  errorAlert: '[data-cy="errorAlert"]',
  companiesList: '[data-cy="companiesList"]',
  companyCard: '[data-cy="companiesList"] li',
  pagination: ".MuiPagination-root",
  paginationButton: ".MuiPaginationItem-root",
  nextPageButton: '[aria-label="Go to next page"]',
  previousPageButton: '[aria-label="Go to previous page"]',
  firstPageButton: '[aria-label="Go to first page"]',
  lastPageButton: '[aria-label="Go to last page"]',
  revenueDialogButton: '[data-cy="revenueDialogButton"]',
  revenueDialog: '[data-cy="revenueDialog"]',
  revenueDialogClose: '[data-cy="revenueDialogClose"]',
  razaoSocial: '[data-cy="razao-social"]',
  nomeFantasia: '[data-cy="nome-fantasia"]',
  cnpj: '[data-cy="cnpj"]',
  municipioEstado: '[data-cy="municipio-estado"]',
  searchBar: '[data-cy="searchBar"]',
  searchBarInput: '[data-cy="searchBarInput"]',
  searchBarIcon: '[data-cy="searchBarIcon"]',
  pageHeading: '[data-cy="pageHeading"]',
  homepageContainer: '[data-cy="homepageContainer"]',
};
