import { Companies } from "@/types";

export const realData: Companies = [
  {
    id: "d98660b3",
    cnpj: "11828067831111",
    estado: "SP",
    municipio: "Ribeirão Preto",
    nome_fantasia: "Fino Pão do Paulo",
    razao_social: "Premium Café do Rafael Ltda.",
  },
  {
    id: "274bc5db",
    cnpj: "47424893272768",
    estado: "CE",
    municipio: "Sobral",
    nome_fantasia: "Caseiro Frutas da Júlia",
    razao_social: "Delicioso Lanches da Clara Ltda.",
  },
  {
    id: "436d0789",
    cnpj: "53517229131137",
    estado: "DF",
    municipio: "Brasília",
    nome_fantasia: "Saboroso Sabores da Júlia",
    razao_social: "Popular Pão do Paulo Ltda.",
  },
  {
    id: "9861883c",
    cnpj: "54324714417591",
    estado: "RS",
    municipio: "Santa Maria",
    nome_fantasia: "Premium Mel da Júlia",
    razao_social: "Fino Flores do Carlos Ltda.",
  },
  {
    id: "a5521451",
    cnpj: "29416697330919",
    estado: "CE",
    municipio: "Maracanaú",
    nome_fantasia: "Natural Doces da Júlia",
    razao_social: "Caseiro Doces do Paulo Ltda.",
  },
  {
    id: "320ee6fd",
    cnpj: "90717232656488",
    estado: "SC",
    municipio: "Florianópolis",
    nome_fantasia: "Premium Queijos da Clara",
    razao_social: "Delicioso Flores do Rafael Ltda.",
  },
  {
    id: "78dec92d",
    cnpj: "41631089201974",
    estado: "DF",
    municipio: "Brasília",
    nome_fantasia: "Delicioso Café do Carlos",
    razao_social: "Natural Frutas da Clara Ltda.",
  },
  {
    id: "e28f758e",
    cnpj: "60402148537067",
    estado: "RS",
    municipio: "Porto Alegre",
    nome_fantasia: "Delicioso Pão do José",
    razao_social: "Caseiro Queijos da Júlia Ltda.",
  },
  {
    id: "7a396ca0",
    cnpj: "52048577410560",
    estado: "SC",
    municipio: "Joinville",
    nome_fantasia: "Doce Sabores do Rafael",
    razao_social: "Doce Sabores do Carlos Ltda.",
  },
  {
    id: "002e28a7",
    cnpj: "80124746515194",
    estado: "DF",
    municipio: "Brasília",
    nome_fantasia: "Delicioso Flores da Júlia",
    razao_social: "Fino Pão da Júlia Ltda.",
  },
  {
    id: "0b11a70d",
    cnpj: "45661084168914",
    estado: "BA",
    municipio: "Camaçari",
    nome_fantasia: "Premium Café do Pedro",
    razao_social: "Fresco Café da Júlia Ltda.",
  },
  {
    id: "72d95248",
    cnpj: "57379088356567",
    estado: "CE",
    municipio: "Sobral",
    nome_fantasia: "Fresco Café da Maria",
    razao_social: "Delicioso Pão do Paulo Ltda.",
  },
];
