name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for Vercel Preview
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          max_timeout: 300

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ steps.vercel_preview_url.outputs.preview_url }}
        env:
          CYPRESS_BASE_URL: ${{ steps.vercel_preview_url.outputs.preview_url }}

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=${{ steps.vercel_preview_url.outputs.preview_url }}
          browser: chrome
          headed: false
        env:
          CYPRESS_BASE_URL: ${{ steps.vercel_preview_url.outputs.preview_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7
